### PR TITLE
Added hotkeys to place keyframes.

### LINKED ISSUE #312: Hotkey to place keyframes
One for position (even when spectating), one for time, one for both and one for spectator. Latter two can probably be bound to NONE by default cause the first two are probably good enough for most people.

### PR DESCRIPTION
**Pull request by TheChocolateOre**
closes #312
I could not build the project, so I have no idea if it runs..

### CODE REVIEW

**Comment by Johni0702** [comment]
Why was this closed?

**Comment by TheChocolateOre** [comment]
I thought it was problematic, cause you didn't report back..

**Comment by Johni0702** [comment]
Nah, it's fine, I just didn't have time to test it yet.

**Comment by TheChocolateOre** [comment]
Oh, my bad.. I didn't test it as well.. I don't have time to deal with it now, you can just copy it into the codebase, it's a few lines addition in 1 method(alt+enter the imports), no big deal.

**Pull request closed without merging**
