### PR TITLE
Update ffmpeg link to the essential release ZIP file directly.

### PR DESCRIPTION
**Pull request by LindaJuffermans**

### CODE REVIEW

**Comment by Johni0702** [comment]
Eh, sorry, I'll hold off on that for a while.

> NOTE: Google Safe Browsing is reporting a false positive for some of the downloads. NONE of the files offered at this site contain any malware.
I'm trying to get hold of a human at Google to rectify this.

https://www.gyan.dev/ffmpeg/builds/

**Comment by LindaJuffermans** [comment]
Note that we're currently already linking to that website for downloads.

https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fwww.gyan.dev%2Fffmpeg%2Fbuilds%2Fffmpeg-release-essentials.zip&hl=en
Reports "No unsafe content found".

**Comment by Johni0702** [comment]
Google Safe Browsing is page specific, if we just link to the main page that should be fairly safe (that's like the main ReplayMod page linking to the docs page, only the docs page got flagged).
I don't particularly trust the search page cause I did throw all the links in there when the docs page got flagged and they all came back as clear as well (great job on that "transparencyreport", Google). I'd rather just play it safe and wait till the warning gets removed.

**Comment by Johni0702** [comment]
Well, they already blocked it anyway, nothing to lose.

**Pull request merged**
